config/routes.rb
Rails.application.routes.draw do

  get 'magazines/index'
  resources :articles, only: [ :create, :show]
  resources :comments, only: [ :create]

  devise_for :users
  get 'home/index'

  root 'magazines#index'

  get 'magazines/:id' => 'magazines#show', as: :magazines_show
  get 'magazines/:id/new_article' => 'magazines#new_article', as: :new_article

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :magazine
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user


  def self.fetch_child_comments(_article_comment)
    where(" parent_id = ? AND parent_class = ?",_article_comment.id, "Comment")
  end

end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create]

  
  
  def show
    @article = Article.find(params[:id])
    @comments = Comment.where(" parent_id = ? AND parent_class = ?",@article.id, "Article")
    @comment = Comment.new
    # @articles = @magazine.articles
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to magazines_show_path(@article.magazine)
  end

  private
  
    def article_params
      params.require(:article).permit(:title, :body, :author, :magazine_id)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :authenticate_user!, only:[ :create]

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to :back
  end

  private
  
    def comment_params
      params.require(:comment).permit(:content, :parent_class, :user_id, :parent_id)
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action :authenticate_user!

  def index
  end

end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  
  before_action :authenticate_user!, only: :new_article

  def index
    @magazines = Magazine.all
  end

  def show
    @magazine = Magazine.find(params[:id])    
    @articles = @magazine.articles
  end

  def new_article
    @magazine = Magazine.find(params[:id])
    @article = @magazine.articles.new
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/articles/_comment_form.html.erb
<% child_comments.each do |child_comment| %>
  <div class= "comment_section">
    User name : <%= child_comment.user.email %>
    <br>
    Comment : <%= child_comment.content %>
    <br>
    <hr>
  </div>
 <% end %>


 <% if current_user.present? %>
 <h1>Reply </h1>
<%= form_for @comment do |f| %>
  <%= f.label    :content %>
  <br>
  <br>
  <%= f.text_field :content %>
  <%= f.hidden_field :parent_class, :value => "Comment" %>
  <%= f.hidden_field :parent_id, :value => "#{_article_comment.id}" %>
  <%= f.hidden_field :user_id, :value => "#{current_user.id}" %>
  <br><br>
  <%= f.submit "Create" %>
<% end %>
<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/articles/show.html.erb
<h1>Articles Details</h1>
Title : <%= @article.title%>
<br>
Body : <%= @article.body %>
<br>
Author : <%= @article.author %>
<br><br>
<b>Comments</b>

<% @comments.each do |_article_comment| %>
  <div class ="article_comment">
    User name : <%= _article_comment.user.email %>
    <br>
    Comment : <%= _article_comment.content %>
    <br>
    <% child_comments = Comment.fetch_child_comments(_article_comment) %>

    <%= render 'comment_form', _article_comment: _article_comment, child_comments: child_comments %>
    <hr>
  </div>

<% end %>

<% if current_user.present? %>
<h1>Create New Comment </h1>


<%= form_for @comment do |f| %>
  <%= f.label    :content %>
  <br>
  <br>
  <%= f.text_area :content, size: "60x12" %>
  <%= f.hidden_field :parent_class, :value => "Article" %>
  <%= f.hidden_field :parent_id, :value => "#{@article.id}" %>
  <%= f.hidden_field :user_id, :value => "#{current_user.id}" %>
  <br><br>
  <%= f.submit "Create" %>
<% end %>

<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GhanshyamApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <% if user_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
    </li>
  <% else %>
    <li>
      <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  
  <li>
    <%= link_to('Magazines', magazines_index_path)  %>
  </li>

  <%= yield %>
</body>
</html>

app/views/magazines/index.html.erb
<h1>Magazines</h1>

<% @magazines.each do |_magazine| %>
  <li>
    <%= link_to "#{_magazine.name}", magazines_show_path(_magazine) %>
  </li>
<% end %>

app/views/magazines/new_article.html.erb
<h1>Create New Article </h1>


<%= form_for @article do |f| %>
  <%= f.label    :title %>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label    :body %>
  <br>
  <br>
  <%= f.text_area :body, size: "60x12" %>
  <br>
  <br>
  <%= f.label    :author %>
  <%= f.text_field :author %>
  <%= f.hidden_field :magazine_id, :value => @magazine.id %>

  <br><br>
  <%= f.submit "Create" %>
<% end %>

app/views/magazines/show.html.erb
<h1> <%= @magazine.name %> </h1>

<i> List of Articles </i>

<% @articles.each do |_article| %>
  <li>
    <%= link_to "#{_article.title}", article_path(_article) %>
  </li>
<% end %>

<br><br>

<%= link_to "Create New Article", new_article_path(@magazine.id) %>